### ISSUE TITLE
Compatible Boards

### ISSUE THREAD

**Issue by Nerdsiah** [hideakitai/ArduinoEigen#1]
This library will only compile for Teensy 3.0 to 3.6. However, it will not compile for Teensy 4.0 or higher. Compiling for 4.0 or higher gives me the following error:

C:\Users\Nerdsiah\Documents\Arduino\libraries\Eigen-0.2.2/ArduinoEigen/ArduinoEigenCommon.h: In function 'constexpr const __FlashStringHelper* F(const char*)':

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy4/avr/pgmspace.h:30:52: error: 'data' declared 'static' in 'constexpr' function
 #define PROGMEM __attribute__((section(".progmem")))
                                                    ^
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy4/avr/pgmspace.h:35:46: note: in expansion of macro 'PROGMEM'
 #define PSTR(str) ({static const char data[] PROGMEM = (str); &data[0];})
                                              ^
C:\Users\Nerdsiah\Documents\Arduino\libraries\Eigen-0.2.2/ArduinoEigen/ArduinoEigenCommon.h:37:57: note: in expansion of macro 'PSTR'
     return reinterpret_cast<const __FlashStringHelper*>(PSTR(str));
                                                         ^
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy4/avr/pgmspace.h:35:60: error: initializer fails to determine size of 'data'
 #define PSTR(str) ({static const char data[] PROGMEM = (str); &data[0];})
                                                            ^
C:\Users\Nerdsiah\Documents\Arduino\libraries\Eigen-0.2.2/ArduinoEigen/ArduinoEigenCommon.h:37:57: note: in expansion of macro 'PSTR'
     return reinterpret_cast<const __FlashStringHelper*>(PSTR(str));
                                                         ^
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy4/avr/pgmspace.h:35:60: error: array must be initialized with a brace-enclosed initializer
 #define PSTR(str) ({static const char data[] PROGMEM = (str); &data[0];})
                                                            ^
C:\Users\Nerdsiah\Documents\Arduino\libraries\Eigen-0.2.2/ArduinoEigen/ArduinoEigenCommon.h:37:57: note: in expansion of macro 'PSTR'
     return reinterpret_cast<const __FlashStringHelper*>(PSTR(str));

Fixed compile issue by commenting out __FlashStringHelper in ArduinoEigenCommon.h.

**Comment by hideakitai** [comment]
@Nerdsiah Thanks, fixed in v0.2.3. Could you try it? The Arduino macros really annoy me...

**Comment by hideakitai** [comment]
I will close this issue but feel free to reopen if you still have a problem.
