### ISSUE TITLE
Read me, does not list the compatible platforms

### ISSUE THREAD

**Issue by adamjvr** [hideakitai/ArduinoEigen#10]
Please update your read me to include a list of what platforms this library can compile for, you only list the platforms that it’s not compatible for.

**Comment by hideakitai** [comment]
It is not realistic, as it should work on all platforms where the C++ standard library is available. If you have one that does not work, please let us know.

**Comment by adamjvr** [comment]
I would really like to use it on the Arduino duet since it’s the most popular arm based Arduino board. Is it possible for that to get support anytime soon? If not, it would be nice to know of a board that it works on so that I can at least design hardware for my application.

**Comment by hideakitai** [comment]
It would be good to select an existing board with the chip you want to use and try to see if example can build it.

**Comment by adamjvr** [comment]
Compiling the example, titled simple for Arduino Due yields this result:

In file included from /home/adam/Arduino/libraries/Eigen/ArduinoEigen.h:6:0,
                 from /tmp/.arduinoIDE-unsaved20231130-5921-1l8g866.2wi9/simple/simple.ino:1:
/home/adam/Arduino/libraries/Eigen/ArduinoEigen/ArduinoEigenCommon.h:8:2: error: #error THIS PLATFORM IS NOT SUPPORTED BECAUSE THERE IS NO STANDARD LIBRARY
 #error THIS PLATFORM IS NOT SUPPORTED BECAUSE THERE IS NO STANDARD LIBRARY
  ^

exit status 1

Compilation error: exit status 1

The reason why I want to use this chip is I have a CNC control motherboard that uses this chip that has five stepper drivers on it, and I want to use that board to control the robotic arm, I have a robot kinematics library that I wrote using ArduinoEigen as a dependency for all the matrix math.

**Comment by hideakitai** [comment]
Due is not supported because C++ standard libraries are not yet available and will not be supported in the future. As mentioned in the README, please consider using EigenArduino or another platform.

**Comment by adamjvr** [comment]
I would, but theres are no list of supportive platforms ;)

**Comment by hideakitai** [comment]
As I said, 

> It is not realistic, as it should work on all platforms where the C++ standard library is available

If you can list all of them, I’m looking forward to your pull request :)
