### ISSUE TITLE
Asser Error when trying to initialize large size vector with less values initialized

### ISSUE THREAD

**Issue by bhupiister** [hideakitai/ArduinoEigen#14]
```
  VectorXd acc(2000);
  acc.setZero();
  acc << 1,2,3,4,5,6,7,8,9,10;
  double maxVal = acc.maxCoeff();
  double minVal = acc.minCoeff();
  double meanVal = acc.mean();

  Serial.printf("Max value: %f\n", maxVal);
  Serial.printf("Min value: %f\n", minVal);
  Serial.printf("Max mean: %f\n", meanVal);
```
  
  I have initialized acc vector with size of 2000. I have taken max size as there is no way to increase the vector size dynamically by push as this will cause heap fragment issue.

I get this error when i try to do it.
`  assert failed: XprType& Eigen::CommaInitializer<MatrixType>::finished() [with XprType = Eigen::Matrix<double, -1, 1>] CommaInitializer.h:124 (((m_row+m_currentBlockRows) == m_xpr.rows() || m_xpr.cols`

Initializing the values like this works

  acc(0) = 1;
  acc(1) = 2;
  acc(2) = 3;
  acc(3) = 4;
  acc(4) = 5;
  acc(5) = 6;
  acc(6) = 7;
  
  But it gives wrong output for mean() function as it divides it by 2000 elements. 
  
  Output:
```
Max value: 7.000000
Min value: 0.000000
Max mean: 0.014000
```

**Comment by hideakitai** [comment]
The source code is here

https://github.com/hideakitai/ArduinoEigen/blob/8f073b5f3bda6058d40ff8987fee3c65486f6eba/ArduinoEigen/Eigen/src/Core/CommaInitializer.h#L124

It says

> Too few coefficients passed to comma initializer (operator<<)

**Comment by bhupiister** [comment]
> The source code is here
> 
> https://github.com/hideakitai/ArduinoEigen/blob/8f073b5f3bda6058d40ff8987fee3c65486f6eba/ArduinoEigen/Eigen/src/Core/CommaInitializer.h#L124
> 
> It says
> 
> > Too few coefficients passed to comma initializer (operator<<)

i want to use it for storing sensor data in real time and then perform operations on it. 

The amount of sensor reading to collect is not fixed, so i initialized a big vector with 2000 and then insert sensor data. How can we do this?

**Comment by hideakitai** [comment]
You can do it without eigen.

```c++
#include <iostream>
#include <algorithm>
#include <numeric>
#include <vector>
#include <cstdlib>
#include <ctime>

int main() {
    // create random elements
    std::srand(std::time(nullptr));
    std::vector<int> vec(100);
    std::generate(vec.begin(), vec.end(), []() { return std::rand() % 1000; });

    // get max and min
    auto max_it = std::max_element(vec.begin(), vec.end());
    auto min_it = std::min_element(vec.begin(), vec.end());

    // get average
    int sum = std::accumulate(vec.begin(), vec.end(), 0);
    double average = static_cast<double>(sum) / vec.size();

    // result
    std::cout << "Maximum Value: " << *max_it << std::endl;
    std::cout << "Minimum Value: " << *min_it << std::endl;
    std::cout << "Average Value: " << average << std::endl;

    return 0;
}
```
```
Maximum Value: 994
Minimum Value: 1
Average Value: 507.98
```

https://wandbox.org/permlink/igYyhnr7ms24sm1w

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
