### ISSUE TITLE
Crash when initializing matrix of size 170x170

### ISSUE THREAD

**Issue by albertbayazidi** [hideakitai/ArduinoEigen#15]
I've observed that creating a very large matrix causes the ESP32 to crash. I was able to replicate this issue by creating a new PlatformIO project and attempting to create a matrix of size 170x170. This resulted in a crash of the ESP32. However, creating a matrix of size 169x169 does not cause a crash, and there is still a significant amount of heap memory available.

Free heap memory: 200308 bytes n = 169
Free heap memory: 201656 bytes n = 168
Free heap memory: 202996 bytes n = 167
and so on.

Error message
ELF file SHA256: 381759b49e6b9a19

E (173) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4

abort() was called at PC 0x400e10db on core 0

Backtrace: 0x40083349:0x3ffe3aa0 0x40087f45:0x3ffe3ac0 0x4008cd21:0x3ffe3ae0 0x400e10db:0x3ffe3b60 0x400e1122:0x3ffe3b80 0x400e1427:0x3ffe3ba0 0x400d13ab:0x3ffe3bc0 0x400d1411:0x3ffe3be0 0x400d147a:0x3ffe3c00 0x400d975f:0x3ffe3c20 0x40082a75:0x3ffe3c50 0x40079306:0x3ffe3c90 |<-CORRUPTED

**Comment by hideakitai** [comment]
How about increasing stack size of main task? 

https://github.com/espressif/arduino-esp32/pull/5173

**Comment by albertbayazidi** [comment]
I'll try this

**Comment by albertbayazidi** [comment]
Increasing the stack size of the main task led to crashes for smaller matrices. I also tried decreasing the stack size so there was more heap memory, but it began crashing because there was too little stack. My understanding is that there is enough heap memory for a 170x170 matrix but it crashes for some other reason.

**Comment by hideakitai** [comment]
Could you give me a minimal code to compile and reproduce the problem?

**Comment by albertbayazidi** [comment]
int n = 169; //will crash for n = 170 on an esp32

Eigen::MatrixXf A(n,n);

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);

}

void loop() {
  size_t freeHeap = ESP.getFreeHeap();
  Serial.printf("Free heap memory: %u bytes\n", freeHeap);
  delay(1000);

}

**Comment by hideakitai** [comment]
Hi @albertbayazidi , sorry for the late reply. I have tried your code and successfully reproduced the problem. However, Eigen's limitation is in the size of rows/cols. Bad alloc exception was thrown from here:

https://github.com/hideakitai/ArduinoEigen/blob/8f073b5f3bda6058d40ff8987fee3c65486f6eba/ArduinoEigen/Eigen/src/Core/PlainObjectBase.h#L48

I couldn't find a way to work around it, so I recommend asking the Eigen community.

**Comment by albertbayazidi** [comment]
I was unable to reproduced the problem for the newest version of Eigen
