### ISSUE TITLE
Does this library need to include the "Arduino.h" header?

### ISSUE THREAD

**Issue by brawner** [hideakitai/ArduinoEigen#17]
This may seem like a dumb question, but I'm not sure I notice anything that actually requires the `Arduino.h` header to be included. I have a use case where I want to run library code on some unit tests that are evaluated on a desktop environment with platformio. I'm trying to avoid a strange dependency on Arduino in those unittests, but this library includes it.

Obviously this library needs to undefined the macros that `Arduino.h` can define, but does that actually require including that header?

**Comment by hideakitai** [comment]
Yes. It is necessary to eliminate the various `#define`s that cause conflicts and build failures when used with Arduino. 

https://github.com/hideakitai/ArduinoEigen/blob/main/ArduinoEigen/ArduinoEigenCommon.h

If you don't need Arduio, you can include `ArduinoEigen/ArduinoEigen/Eigen` directly and use it in your C++ program instead of including `ArduinoEigen.h`.

**Comment by brawner** [comment]
I agree that including `ArduinoEigenCommon.h` before including `Eigen` headers is necessary. But including the actual `Arduino.h` doesn't "eliminate the various `#defines`", it just adds a dependency to all of Arduino for this library. 

I wanted to check if there were any types, functions, or macros that needed be pulled in from `Arduino.h` to be used with this library. It does not appear to be the case.

**Comment by hideakitai** [comment]
Please close this issue if it is solved

**Comment by brawner** [comment]
This issue is a request to remove the `Arduino.h` header from your includes. If you don't plan on doing that, then I would suggest labeling this a "won't fix"

**Comment by hideakitai** [comment]
I couldn’t understand why you requested removing Arduino.h. 

As we mentioned, you must include all annoying macros and #undef + re-declare them to use Eigen with the Arduino platform.

You can also include Eigen directly if you don't need the fixes for the Arduino platform.

What is the reason you request it?

**Comment by hideakitai** [comment]
Also, since this is open source, you can contribute to it if you have an idea to improve it.

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
