### ISSUE TITLE
can not find <cmath>  why?

### ISSUE THREAD

**Issue by wwwtd** [hideakitai/ArduinoEigen#18]
libraries\Eigen/ArduinoEigen/Eigen/src/Core/util/Macros.h:679:10: fatal error: cmath: No such file or directory
 #include <cmath>
          ^~~~~~~
compilation terminated.
exit status 1
 Arduino Uno 
can not   use this program ? how can I do?

in this :

#include <cmath>  -----> ERROR
#ifndef EIGEN_HAS_C99_MATH
#if EIGEN_MAX_CPP_VER>=11 && \
    ((defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901))       \
  || (defined(__GNUC__) && defined(_GLIBCXX_USE_C99)) \
  || (defined(_LIBCPP_VERSION) && !defined(_MSC_VER)) \
  || (EIGEN_COMP_MSVC >= 1900) || defined(SYCL_DEVICE_ONLY))
  #define EIGEN_HAS_C99_MATH 1
#else
  #define EIGEN_HAS_C99_MATH 0
#endif
#endif

**Comment by hideakitai** [comment]
Please refer to README for Uno

https://github.com/hideakitai/ArduinoEigen?tab=readme-ov-file#note

**Comment by wwwtd** [comment]
Thank you！
