### ISSUE TITLE
Nano 33 BLE complier errors

### ISSUE THREAD

**Issue by thetechwells** [hideakitai/ArduinoEigen#2]
In file included from ***AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\cores\arduino/Arduino.h:76:0,
                 from ***\AppData\Local\Temp\arduino-sketch-E55E67B8DEFCD898E43FF53D1C5851C5\sketch\simple.ino.cpp:1:
***Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function 'void Eigen::internal::lhs_process_one_packet<nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket, RhsPacket, ResPacket, GEBPTraits, LinearMapper, DataMapper>::operator()(const DataMapper&, const LhsScalar*, const RhsScalar*, ResScalar, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index, int, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index)':
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:83:16: error: lvalue required as unary '&' operand
 #define D0  (0u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1270:73: note: in expansion of macro 'D0'
           peeled_kc_onestep(1, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                         ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:84:16: error: lvalue required as unary '&' operand
 #define D1  (1u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1270:78: note: in expansion of macro 'D1'
           peeled_kc_onestep(1, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                              ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:85:16: error: lvalue required as unary '&' operand
 #define D2  (2u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1270:83: note: in expansion of macro 'D2'
           peeled_kc_onestep(1, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                   ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:86:16: error: lvalue required as unary '&' operand
 #define D3  (3u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1270:88: note: in expansion of macro 'D3'
           peeled_kc_onestep(1, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                        ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:83:16: error: lvalue required as unary '&' operand
 #define D0  (0u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1272:73: note: in expansion of macro 'D0'
           peeled_kc_onestep(3, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                         ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:84:16: error: lvalue required as unary '&' operand
 #define D1  (1u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1272:78: note: in expansion of macro 'D1'
           peeled_kc_onestep(3, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                              ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:85:16: error: lvalue required as unary '&' operand
 #define D2  (2u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1272:83: note: in expansion of macro 'D2'
           peeled_kc_onestep(3, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                   ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:86:16: error: lvalue required as unary '&' operand
 #define D3  (3u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1272:88: note: in expansion of macro 'D3'
           peeled_kc_onestep(3, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                        ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:83:16: error: lvalue required as unary '&' operand
 #define D0  (0u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1275:73: note: in expansion of macro 'D0'
           peeled_kc_onestep(5, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                         ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:84:16: error: lvalue required as unary '&' operand
 #define D1  (1u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1275:78: note: in expansion of macro 'D1'
           peeled_kc_onestep(5, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                              ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:85:16: error: lvalue required as unary '&' operand
 #define D2  (2u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1275:83: note: in expansion of macro 'D2'
           peeled_kc_onestep(5, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                   ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:86:16: error: lvalue required as unary '&' operand
 #define D3  (3u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1275:88: note: in expansion of macro 'D3'
           peeled_kc_onestep(5, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                        ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:83:16: error: lvalue required as unary '&' operand
 #define D0  (0u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1277:73: note: in expansion of macro 'D0'
           peeled_kc_onestep(7, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                         ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:84:16: error: lvalue required as unary '&' operand
 #define D1  (1u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1277:78: note: in expansion of macro 'D1'
           peeled_kc_onestep(7, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                              ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:85:16: error: lvalue required as unary '&' operand
 #define D2  (2u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1277:83: note: in expansion of macro 'D2'
           peeled_kc_onestep(7, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                   ^~
***\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\variants\ARDUINO_NANO33BLE/pins_arduino.h:86:16: error: lvalue required as unary '&' operand
 #define D3  (3u)
                ^
***\Documents\Arduino\libraries\Eigen/ArduinoEigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1277:88: note: in expansion of macro 'D3'
           peeled_kc_onestep(7, blA, blB, traits, &A1, &rhs_panel, &T0, &D0, &D1, &D2, &D3);
                                                                                        ^~

exit status 1

Compilation error: exit status 1

**Comment by hideakitai** [comment]
This problem has been resolved with the above issue/pr.
