### ISSUE TITLE
arduino:sam support

### ISSUE THREAD

**Issue by henriksod** [hideakitai/ArduinoEigen#3]
Hello, I am trying to use this library with an Arduino Due, based on 32-bits ARM Cortex-M3 (SAM core).

Have this library been tried with Arduino Due before? Would be really helpful if support could be added.

I get the following error:
`error: #error THIS PLATFORM IS NOT SUPPORTED BECAUSE THERE IS NO STANDARD LIBRARY`

Compiling with:
`arduino-cli compile --fqbn arduino:sam:arduino_due_x_dbg sketch.ino -v`

**Comment by pixmusix** [comment]
Bumping this.
@hideakitai  what is it from stand-lib that you need to make this work? 
Maybe we can fork it from somewhere, paste it in a black box, and treat it like an API? 
It's a little dirty but par for the course.

Happy to help make this work. This Lib looks right for drawing to an LED matrix and Large LED Matrices may needs many digital outs. Supporting the Due is worth it.

**Comment by hideakitai** [comment]
It is difficult to support DUE because it doesn't support C++ standard library. Please use https://github.com/vancegroup/EigenArduino for such Atmel's board
