### ISSUE TITLE
compilation terminated.

### ISSUE THREAD

**Issue by MohanadMahran** [hideakitai/ArduinoEigen#4]
Arduino\libraries\Bolder_Flight_Systems_Eigen\src/Eigen/src/Core/products/Parallelizer.h:14:10: fatal error: atomic: No such file or directory
 #include <atomic>
          ^~~~~~~~

**Comment by hideakitai** [comment]
I think it's a conflict between bolder flight's eigen library. You can use bolder flight's eigen instead of this library

https://github.com/bolderflight/eigen
