### ISSUE TITLE
STM32Duino Compilation Error

### ISSUE THREAD

**Issue by SparrowTheNerd** [hideakitai/ArduinoEigen#9]
`.pio\libdeps\genericSTM32F446RE\ArduinoEigen/ArduinoEigen/Eigen/src/Core/util/StaticAssert.h:158:51: error: static assertion failed: THIS_METHOD_IS_ONLY_FOR_VECTORS_OF_A_SPECIFIC_SIZE`

This error occurs upon attempting to compile code using the STM32Duino framework and the ArduinoEigen library. The error acts upon the following piece of code in the StaticAssert.h file, beginning at line 156:
`// static assertion failing if the type \a TYPE is not a vector type of the given size
#define EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(TYPE, SIZE) \
EIGEN_STATIC_ASSERT(TYPE::IsVectorAtCompileTime && TYPE::SizeAtCompileTime==SIZE, \
                      THIS_METHOD_IS_ONLY_FOR_VECTORS_OF_A_SPECIFIC_SIZE)`

The error highlights the && operator as the issue.

**Comment by hideakitai** [comment]
Can you compile an example sketch on your board? It seems to be an error of Eigen itself. An example sketch can be compiled in my environment on a genericSTM32F4 board. Please give me more information:

- Your board (genericSTM32F4 series?)
- Your minimal source code that can be compiled and reproduce the problem

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
